services:
  postgres:
    image: postgres:16
    container_name: yugioh_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - yugioh_network

volumes:
  postgres_data:

networks:
  yugioh_network:
    external: true